version: 2.1

orbs:
  docker: circleci/node@4.2.1

jobs:
  run_tests:
    working_directory: ~/react-app
    docker:
      - image: circleci/node:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
#      - run:
#         name: test
#         command: npm test
  build_docker_image:
    docker:
      - image: cimg/node:latest
      auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
#      - setup_remote_docker:
#          docker_layer_caching: true
#      - run:
#          name: Setup Tag
#	   command: echo "export TAG-0.1.$CIRCLE_SHA1" >> $BASH_ENV
      - run:
          name: Build docker image
          command: docker build -t ci-image:latest .
# run_integration_tests:
#   docker:
#     - image: circleci/node:13.10.1
#   steps:
#     - checkout
  
workflows:
  version: 2
  build_test:
    jobs:
       - run_tests
#      - node/test:
#          matrix:
#	    parameters:
#	      version:
#	        - 14.0.0
#		- 13.11.0
#		- 12.16.0
#       - docker/publish:
#          image: harishvarma44/react-nginx-demo
#          dockerfile: Dockerfile
#          requires:
#           - build_docker_image
#          filters:
#            branches:
#              only: 
#               - master
       - build_docker_image:
          requires:
            - run_tests
